language: java
dist: trusty

jdk:
  - openjdk11

script:
  - mvn -B test jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=mehmetazizyirik -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=MehmetAzizYirik_MAYGEN -Dsonar.login=$SONAR_TOKEN
